### ISSUE TITLE
Data gen errors: gym.error.UnregisteredEnv: No registered env with id: ColorChangingRL-5-5-static-10-v0

### ISSUE THREAD

**Issue by syyunn** [dido1998/CausalMBRL#1]
I am trying to reproduce the code and start by generating chemical env data, however, when I run `bash scripts/chem_data.sh 5 5 chain5 10 static` in the root dir, it returns error like:

```bash
INFO: Making new env: ColorChangingRL-5-5-static-10-v0
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'ColorChangingRL-5-5-static-10-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_gen/env.py", line 196, in <module>
    main()
  File "data_gen/env.py", line 177, in main
    with gym.make(args.env_id) as env:
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: ColorChangingRL-5-5-static-10-v0
INFO: Making new env: ColorChangingRL-5-5-static-10-v0
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'ColorChangingRL-5-5-static-10-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_gen/env.py", line 196, in <module>
    main()
  File "data_gen/env.py", line 177, in main
    with gym.make(args.env_id) as env:
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: ColorChangingRL-5-5-static-10-v0
INFO: Making new env: ColorChangingRL-5-5-static-10-v0
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'ColorChangingRL-5-5-static-10-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_gen/env.py", line 196, in <module>
    main()
  File "data_gen/env.py", line 177, in main
    with gym.make(args.env_id) as env:
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/user/anaconda3/envs/cmbrl/lib/python3.7/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: ColorChangingRL-5-5-static-10-v0
``` 

Any suggestion how to solve this error?

**Comment by dido1998** [comment]
Could you change `static->Static` i.e. `bash scripts/chem_data.sh 5 5 chain5 10 Static`
